package com.epeisong.model;

import java.io.Serializable;

public class ComplainTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payer_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer payerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payer_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private String payerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payer_guarantee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer payerGuaranteeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payer_guarantee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private String payerGuaranteeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer payeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private String payeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payee_guarantee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer payeeGuaranteeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payee_guarantee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private String payeeGuaranteeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.trading_platform_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer tradingPlatformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.trading_platform_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private String tradingPlatformName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.deal_bill_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer dealBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.deal_bill_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private String dealBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.status
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payer_guarantee_amount_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer payerGuaranteeAmountResultType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payer_guarantee_amount_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer payerGuaranteeAmountResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payee_guarantee_amount_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer payeeGuaranteeAmountResultType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.payee_guarantee_amount_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer payeeGuaranteeAmountResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.info_fee_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer infoFeeResultType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.info_fee_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer infoFeeResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.create_date
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.update_date
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Long updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.sync_index
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private Integer syncIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_task.note
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table complain_task
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.id
     *
     * @return the value of complain_task.id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.id
     *
     * @param id the value for complain_task.id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payer_id
     *
     * @return the value of complain_task.payer_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getPayerId() {
        return payerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payer_id
     *
     * @param payerId the value for complain_task.payer_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayerId(Integer payerId) {
        this.payerId = payerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payer_name
     *
     * @return the value of complain_task.payer_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payer_name
     *
     * @param payerName the value for complain_task.payer_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payer_guarantee_id
     *
     * @return the value of complain_task.payer_guarantee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getPayerGuaranteeId() {
        return payerGuaranteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payer_guarantee_id
     *
     * @param payerGuaranteeId the value for complain_task.payer_guarantee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayerGuaranteeId(Integer payerGuaranteeId) {
        this.payerGuaranteeId = payerGuaranteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payer_guarantee_name
     *
     * @return the value of complain_task.payer_guarantee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public String getPayerGuaranteeName() {
        return payerGuaranteeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payer_guarantee_name
     *
     * @param payerGuaranteeName the value for complain_task.payer_guarantee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayerGuaranteeName(String payerGuaranteeName) {
        this.payerGuaranteeName = payerGuaranteeName == null ? null : payerGuaranteeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payee_id
     *
     * @return the value of complain_task.payee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getPayeeId() {
        return payeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payee_id
     *
     * @param payeeId the value for complain_task.payee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayeeId(Integer payeeId) {
        this.payeeId = payeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payee_name
     *
     * @return the value of complain_task.payee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payee_name
     *
     * @param payeeName the value for complain_task.payee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName == null ? null : payeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payee_guarantee_id
     *
     * @return the value of complain_task.payee_guarantee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getPayeeGuaranteeId() {
        return payeeGuaranteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payee_guarantee_id
     *
     * @param payeeGuaranteeId the value for complain_task.payee_guarantee_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayeeGuaranteeId(Integer payeeGuaranteeId) {
        this.payeeGuaranteeId = payeeGuaranteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payee_guarantee_name
     *
     * @return the value of complain_task.payee_guarantee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public String getPayeeGuaranteeName() {
        return payeeGuaranteeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payee_guarantee_name
     *
     * @param payeeGuaranteeName the value for complain_task.payee_guarantee_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayeeGuaranteeName(String payeeGuaranteeName) {
        this.payeeGuaranteeName = payeeGuaranteeName == null ? null : payeeGuaranteeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.trading_platform_id
     *
     * @return the value of complain_task.trading_platform_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getTradingPlatformId() {
        return tradingPlatformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.trading_platform_id
     *
     * @param tradingPlatformId the value for complain_task.trading_platform_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setTradingPlatformId(Integer tradingPlatformId) {
        this.tradingPlatformId = tradingPlatformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.trading_platform_name
     *
     * @return the value of complain_task.trading_platform_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public String getTradingPlatformName() {
        return tradingPlatformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.trading_platform_name
     *
     * @param tradingPlatformName the value for complain_task.trading_platform_name
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setTradingPlatformName(String tradingPlatformName) {
        this.tradingPlatformName = tradingPlatformName == null ? null : tradingPlatformName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.deal_bill_type
     *
     * @return the value of complain_task.deal_bill_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getDealBillType() {
        return dealBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.deal_bill_type
     *
     * @param dealBillType the value for complain_task.deal_bill_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setDealBillType(Integer dealBillType) {
        this.dealBillType = dealBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.deal_bill_id
     *
     * @return the value of complain_task.deal_bill_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public String getDealBillId() {
        return dealBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.deal_bill_id
     *
     * @param dealBillId the value for complain_task.deal_bill_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setDealBillId(String dealBillId) {
        this.dealBillId = dealBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.status
     *
     * @return the value of complain_task.status
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.status
     *
     * @param status the value for complain_task.status
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payer_guarantee_amount_result_type
     *
     * @return the value of complain_task.payer_guarantee_amount_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getPayerGuaranteeAmountResultType() {
        return payerGuaranteeAmountResultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payer_guarantee_amount_result_type
     *
     * @param payerGuaranteeAmountResultType the value for complain_task.payer_guarantee_amount_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayerGuaranteeAmountResultType(Integer payerGuaranteeAmountResultType) {
        this.payerGuaranteeAmountResultType = payerGuaranteeAmountResultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payer_guarantee_amount_result_id
     *
     * @return the value of complain_task.payer_guarantee_amount_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getPayerGuaranteeAmountResultId() {
        return payerGuaranteeAmountResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payer_guarantee_amount_result_id
     *
     * @param payerGuaranteeAmountResultId the value for complain_task.payer_guarantee_amount_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayerGuaranteeAmountResultId(Integer payerGuaranteeAmountResultId) {
        this.payerGuaranteeAmountResultId = payerGuaranteeAmountResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payee_guarantee_amount_result_type
     *
     * @return the value of complain_task.payee_guarantee_amount_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getPayeeGuaranteeAmountResultType() {
        return payeeGuaranteeAmountResultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payee_guarantee_amount_result_type
     *
     * @param payeeGuaranteeAmountResultType the value for complain_task.payee_guarantee_amount_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayeeGuaranteeAmountResultType(Integer payeeGuaranteeAmountResultType) {
        this.payeeGuaranteeAmountResultType = payeeGuaranteeAmountResultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.payee_guarantee_amount_result_id
     *
     * @return the value of complain_task.payee_guarantee_amount_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getPayeeGuaranteeAmountResultId() {
        return payeeGuaranteeAmountResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.payee_guarantee_amount_result_id
     *
     * @param payeeGuaranteeAmountResultId the value for complain_task.payee_guarantee_amount_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setPayeeGuaranteeAmountResultId(Integer payeeGuaranteeAmountResultId) {
        this.payeeGuaranteeAmountResultId = payeeGuaranteeAmountResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.info_fee_result_type
     *
     * @return the value of complain_task.info_fee_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getInfoFeeResultType() {
        return infoFeeResultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.info_fee_result_type
     *
     * @param infoFeeResultType the value for complain_task.info_fee_result_type
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setInfoFeeResultType(Integer infoFeeResultType) {
        this.infoFeeResultType = infoFeeResultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.info_fee_result_id
     *
     * @return the value of complain_task.info_fee_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getInfoFeeResultId() {
        return infoFeeResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.info_fee_result_id
     *
     * @param infoFeeResultId the value for complain_task.info_fee_result_id
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setInfoFeeResultId(Integer infoFeeResultId) {
        this.infoFeeResultId = infoFeeResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.create_date
     *
     * @return the value of complain_task.create_date
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.create_date
     *
     * @param createDate the value for complain_task.create_date
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.update_date
     *
     * @return the value of complain_task.update_date
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Long getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.update_date
     *
     * @param updateDate the value for complain_task.update_date
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.sync_index
     *
     * @return the value of complain_task.sync_index
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public Integer getSyncIndex() {
        return syncIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.sync_index
     *
     * @param syncIndex the value for complain_task.sync_index
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setSyncIndex(Integer syncIndex) {
        this.syncIndex = syncIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_task.note
     *
     * @return the value of complain_task.note
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_task.note
     *
     * @param note the value for complain_task.note
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_task
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComplainTask other = (ComplainTask) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayerId() == null ? other.getPayerId() == null : this.getPayerId().equals(other.getPayerId()))
            && (this.getPayerName() == null ? other.getPayerName() == null : this.getPayerName().equals(other.getPayerName()))
            && (this.getPayerGuaranteeId() == null ? other.getPayerGuaranteeId() == null : this.getPayerGuaranteeId().equals(other.getPayerGuaranteeId()))
            && (this.getPayerGuaranteeName() == null ? other.getPayerGuaranteeName() == null : this.getPayerGuaranteeName().equals(other.getPayerGuaranteeName()))
            && (this.getPayeeId() == null ? other.getPayeeId() == null : this.getPayeeId().equals(other.getPayeeId()))
            && (this.getPayeeName() == null ? other.getPayeeName() == null : this.getPayeeName().equals(other.getPayeeName()))
            && (this.getPayeeGuaranteeId() == null ? other.getPayeeGuaranteeId() == null : this.getPayeeGuaranteeId().equals(other.getPayeeGuaranteeId()))
            && (this.getPayeeGuaranteeName() == null ? other.getPayeeGuaranteeName() == null : this.getPayeeGuaranteeName().equals(other.getPayeeGuaranteeName()))
            && (this.getTradingPlatformId() == null ? other.getTradingPlatformId() == null : this.getTradingPlatformId().equals(other.getTradingPlatformId()))
            && (this.getTradingPlatformName() == null ? other.getTradingPlatformName() == null : this.getTradingPlatformName().equals(other.getTradingPlatformName()))
            && (this.getDealBillType() == null ? other.getDealBillType() == null : this.getDealBillType().equals(other.getDealBillType()))
            && (this.getDealBillId() == null ? other.getDealBillId() == null : this.getDealBillId().equals(other.getDealBillId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getPayerGuaranteeAmountResultType() == null ? other.getPayerGuaranteeAmountResultType() == null : this.getPayerGuaranteeAmountResultType().equals(other.getPayerGuaranteeAmountResultType()))
            && (this.getPayerGuaranteeAmountResultId() == null ? other.getPayerGuaranteeAmountResultId() == null : this.getPayerGuaranteeAmountResultId().equals(other.getPayerGuaranteeAmountResultId()))
            && (this.getPayeeGuaranteeAmountResultType() == null ? other.getPayeeGuaranteeAmountResultType() == null : this.getPayeeGuaranteeAmountResultType().equals(other.getPayeeGuaranteeAmountResultType()))
            && (this.getPayeeGuaranteeAmountResultId() == null ? other.getPayeeGuaranteeAmountResultId() == null : this.getPayeeGuaranteeAmountResultId().equals(other.getPayeeGuaranteeAmountResultId()))
            && (this.getInfoFeeResultType() == null ? other.getInfoFeeResultType() == null : this.getInfoFeeResultType().equals(other.getInfoFeeResultType()))
            && (this.getInfoFeeResultId() == null ? other.getInfoFeeResultId() == null : this.getInfoFeeResultId().equals(other.getInfoFeeResultId()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getSyncIndex() == null ? other.getSyncIndex() == null : this.getSyncIndex().equals(other.getSyncIndex()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_task
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayerId() == null) ? 0 : getPayerId().hashCode());
        result = prime * result + ((getPayerName() == null) ? 0 : getPayerName().hashCode());
        result = prime * result + ((getPayerGuaranteeId() == null) ? 0 : getPayerGuaranteeId().hashCode());
        result = prime * result + ((getPayerGuaranteeName() == null) ? 0 : getPayerGuaranteeName().hashCode());
        result = prime * result + ((getPayeeId() == null) ? 0 : getPayeeId().hashCode());
        result = prime * result + ((getPayeeName() == null) ? 0 : getPayeeName().hashCode());
        result = prime * result + ((getPayeeGuaranteeId() == null) ? 0 : getPayeeGuaranteeId().hashCode());
        result = prime * result + ((getPayeeGuaranteeName() == null) ? 0 : getPayeeGuaranteeName().hashCode());
        result = prime * result + ((getTradingPlatformId() == null) ? 0 : getTradingPlatformId().hashCode());
        result = prime * result + ((getTradingPlatformName() == null) ? 0 : getTradingPlatformName().hashCode());
        result = prime * result + ((getDealBillType() == null) ? 0 : getDealBillType().hashCode());
        result = prime * result + ((getDealBillId() == null) ? 0 : getDealBillId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getPayerGuaranteeAmountResultType() == null) ? 0 : getPayerGuaranteeAmountResultType().hashCode());
        result = prime * result + ((getPayerGuaranteeAmountResultId() == null) ? 0 : getPayerGuaranteeAmountResultId().hashCode());
        result = prime * result + ((getPayeeGuaranteeAmountResultType() == null) ? 0 : getPayeeGuaranteeAmountResultType().hashCode());
        result = prime * result + ((getPayeeGuaranteeAmountResultId() == null) ? 0 : getPayeeGuaranteeAmountResultId().hashCode());
        result = prime * result + ((getInfoFeeResultType() == null) ? 0 : getInfoFeeResultType().hashCode());
        result = prime * result + ((getInfoFeeResultId() == null) ? 0 : getInfoFeeResultId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getSyncIndex() == null) ? 0 : getSyncIndex().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_task
     *
     * @mbggenerated Thu Mar 12 16:17:33 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payerId=").append(payerId);
        sb.append(", payerName=").append(payerName);
        sb.append(", payerGuaranteeId=").append(payerGuaranteeId);
        sb.append(", payerGuaranteeName=").append(payerGuaranteeName);
        sb.append(", payeeId=").append(payeeId);
        sb.append(", payeeName=").append(payeeName);
        sb.append(", payeeGuaranteeId=").append(payeeGuaranteeId);
        sb.append(", payeeGuaranteeName=").append(payeeGuaranteeName);
        sb.append(", tradingPlatformId=").append(tradingPlatformId);
        sb.append(", tradingPlatformName=").append(tradingPlatformName);
        sb.append(", dealBillType=").append(dealBillType);
        sb.append(", dealBillId=").append(dealBillId);
        sb.append(", status=").append(status);
        sb.append(", payerGuaranteeAmountResultType=").append(payerGuaranteeAmountResultType);
        sb.append(", payerGuaranteeAmountResultId=").append(payerGuaranteeAmountResultId);
        sb.append(", payeeGuaranteeAmountResultType=").append(payeeGuaranteeAmountResultType);
        sb.append(", payeeGuaranteeAmountResultId=").append(payeeGuaranteeAmountResultId);
        sb.append(", infoFeeResultType=").append(infoFeeResultType);
        sb.append(", infoFeeResultId=").append(infoFeeResultId);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", syncIndex=").append(syncIndex);
        sb.append(", note=").append(note);
        sb.append("]");
        return sb.toString();
    }
}