package com.epeisong.net.ws.utils;

import java.io.Serializable;

public class BankCard implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.id
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.wallet_id
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private Integer walletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.wallet_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private String walletName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.card_type
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private Integer cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.bank_code
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.bank_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.card_number
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.real_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.id_type
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private Integer idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.identity_number
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private String identityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.open_bank_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private String openBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.region_code
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private Integer regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.region_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.create_date
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.update_date
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private Long updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bank_card
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.id
     *
     * @return the value of bank_card.id
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.id
     *
     * @param id the value for bank_card.id
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.wallet_id
     *
     * @return the value of bank_card.wallet_id
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public Integer getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.wallet_id
     *
     * @param walletId the value for bank_card.wallet_id
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setWalletId(Integer walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.wallet_name
     *
     * @return the value of bank_card.wallet_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public String getWalletName() {
        return walletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.wallet_name
     *
     * @param walletName the value for bank_card.wallet_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setWalletName(String walletName) {
        this.walletName = walletName == null ? null : walletName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.card_type
     *
     * @return the value of bank_card.card_type
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public Integer getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.card_type
     *
     * @param cardType the value for bank_card.card_type
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.bank_code
     *
     * @return the value of bank_card.bank_code
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.bank_code
     *
     * @param bankCode the value for bank_card.bank_code
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.bank_name
     *
     * @return the value of bank_card.bank_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.bank_name
     *
     * @param bankName the value for bank_card.bank_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.card_number
     *
     * @return the value of bank_card.card_number
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.card_number
     *
     * @param cardNumber the value for bank_card.card_number
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber == null ? null : cardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.real_name
     *
     * @return the value of bank_card.real_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.real_name
     *
     * @param realName the value for bank_card.real_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.id_type
     *
     * @return the value of bank_card.id_type
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public Integer getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.id_type
     *
     * @param idType the value for bank_card.id_type
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setIdType(Integer idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.identity_number
     *
     * @return the value of bank_card.identity_number
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public String getIdentityNumber() {
        return identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.identity_number
     *
     * @param identityNumber the value for bank_card.identity_number
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setIdentityNumber(String identityNumber) {
        this.identityNumber = identityNumber == null ? null : identityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.open_bank_name
     *
     * @return the value of bank_card.open_bank_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public String getOpenBankName() {
        return openBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.open_bank_name
     *
     * @param openBankName the value for bank_card.open_bank_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setOpenBankName(String openBankName) {
        this.openBankName = openBankName == null ? null : openBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.region_code
     *
     * @return the value of bank_card.region_code
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public Integer getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.region_code
     *
     * @param regionCode the value for bank_card.region_code
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setRegionCode(Integer regionCode) {
        this.regionCode = regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.region_name
     *
     * @return the value of bank_card.region_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.region_name
     *
     * @param regionName the value for bank_card.region_name
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.create_date
     *
     * @return the value of bank_card.create_date
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.create_date
     *
     * @param createDate the value for bank_card.create_date
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.update_date
     *
     * @return the value of bank_card.update_date
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public Long getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.update_date
     *
     * @param updateDate the value for bank_card.update_date
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BankCard other = (BankCard) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWalletId() == null ? other.getWalletId() == null : this.getWalletId().equals(other.getWalletId()))
            && (this.getWalletName() == null ? other.getWalletName() == null : this.getWalletName().equals(other.getWalletName()))
            && (this.getCardType() == null ? other.getCardType() == null : this.getCardType().equals(other.getCardType()))
            && (this.getBankCode() == null ? other.getBankCode() == null : this.getBankCode().equals(other.getBankCode()))
            && (this.getBankName() == null ? other.getBankName() == null : this.getBankName().equals(other.getBankName()))
            && (this.getCardNumber() == null ? other.getCardNumber() == null : this.getCardNumber().equals(other.getCardNumber()))
            && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))
            && (this.getIdType() == null ? other.getIdType() == null : this.getIdType().equals(other.getIdType()))
            && (this.getIdentityNumber() == null ? other.getIdentityNumber() == null : this.getIdentityNumber().equals(other.getIdentityNumber()))
            && (this.getOpenBankName() == null ? other.getOpenBankName() == null : this.getOpenBankName().equals(other.getOpenBankName()))
            && (this.getRegionCode() == null ? other.getRegionCode() == null : this.getRegionCode().equals(other.getRegionCode()))
            && (this.getRegionName() == null ? other.getRegionName() == null : this.getRegionName().equals(other.getRegionName()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWalletId() == null) ? 0 : getWalletId().hashCode());
        result = prime * result + ((getWalletName() == null) ? 0 : getWalletName().hashCode());
        result = prime * result + ((getCardType() == null) ? 0 : getCardType().hashCode());
        result = prime * result + ((getBankCode() == null) ? 0 : getBankCode().hashCode());
        result = prime * result + ((getBankName() == null) ? 0 : getBankName().hashCode());
        result = prime * result + ((getCardNumber() == null) ? 0 : getCardNumber().hashCode());
        result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
        result = prime * result + ((getIdType() == null) ? 0 : getIdType().hashCode());
        result = prime * result + ((getIdentityNumber() == null) ? 0 : getIdentityNumber().hashCode());
        result = prime * result + ((getOpenBankName() == null) ? 0 : getOpenBankName().hashCode());
        result = prime * result + ((getRegionCode() == null) ? 0 : getRegionCode().hashCode());
        result = prime * result + ((getRegionName() == null) ? 0 : getRegionName().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Thu Jan 29 09:37:02 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", walletId=").append(walletId);
        sb.append(", walletName=").append(walletName);
        sb.append(", cardType=").append(cardType);
        sb.append(", bankCode=").append(bankCode);
        sb.append(", bankName=").append(bankName);
        sb.append(", cardNumber=").append(cardNumber);
        sb.append(", realName=").append(realName);
        sb.append(", idType=").append(idType);
        sb.append(", identityNumber=").append(identityNumber);
        sb.append(", openBankName=").append(openBankName);
        sb.append(", regionCode=").append(regionCode);
        sb.append(", regionName=").append(regionName);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}