package com.epeisong.net.ws.utils;

import java.io.Serializable;

public class BondWalletDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.payer_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer payerWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.payee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer payeeWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.payer_guarantee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer payerGuaranteeWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.payee_guarantee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer payeeGuaranteeWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.amount
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.deal_bill_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer dealBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.deal_bill_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer dealBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.source_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer sourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.source_name
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.source_account
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private String sourceAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.operation_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Integer operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.payer_desc
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private String payerDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.payee_desc
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private String payeeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet_detail.create_date
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bond_wallet_detail
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.id
     *
     * @return the value of bond_wallet_detail.id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.id
     *
     * @param id the value for bond_wallet_detail.id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.payer_wallet_id
     *
     * @return the value of bond_wallet_detail.payer_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getPayerWalletId() {
        return payerWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.payer_wallet_id
     *
     * @param payerWalletId the value for bond_wallet_detail.payer_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setPayerWalletId(Integer payerWalletId) {
        this.payerWalletId = payerWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.payee_wallet_id
     *
     * @return the value of bond_wallet_detail.payee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getPayeeWalletId() {
        return payeeWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.payee_wallet_id
     *
     * @param payeeWalletId the value for bond_wallet_detail.payee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setPayeeWalletId(Integer payeeWalletId) {
        this.payeeWalletId = payeeWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.payer_guarantee_wallet_id
     *
     * @return the value of bond_wallet_detail.payer_guarantee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getPayerGuaranteeWalletId() {
        return payerGuaranteeWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.payer_guarantee_wallet_id
     *
     * @param payerGuaranteeWalletId the value for bond_wallet_detail.payer_guarantee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setPayerGuaranteeWalletId(Integer payerGuaranteeWalletId) {
        this.payerGuaranteeWalletId = payerGuaranteeWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.payee_guarantee_wallet_id
     *
     * @return the value of bond_wallet_detail.payee_guarantee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getPayeeGuaranteeWalletId() {
        return payeeGuaranteeWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.payee_guarantee_wallet_id
     *
     * @param payeeGuaranteeWalletId the value for bond_wallet_detail.payee_guarantee_wallet_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setPayeeGuaranteeWalletId(Integer payeeGuaranteeWalletId) {
        this.payeeGuaranteeWalletId = payeeGuaranteeWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.amount
     *
     * @return the value of bond_wallet_detail.amount
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.amount
     *
     * @param amount the value for bond_wallet_detail.amount
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.deal_bill_type
     *
     * @return the value of bond_wallet_detail.deal_bill_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getDealBillType() {
        return dealBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.deal_bill_type
     *
     * @param dealBillType the value for bond_wallet_detail.deal_bill_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setDealBillType(Integer dealBillType) {
        this.dealBillType = dealBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.deal_bill_id
     *
     * @return the value of bond_wallet_detail.deal_bill_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getDealBillId() {
        return dealBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.deal_bill_id
     *
     * @param dealBillId the value for bond_wallet_detail.deal_bill_id
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setDealBillId(Integer dealBillId) {
        this.dealBillId = dealBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.source_type
     *
     * @return the value of bond_wallet_detail.source_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.source_type
     *
     * @param sourceType the value for bond_wallet_detail.source_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.source_name
     *
     * @return the value of bond_wallet_detail.source_name
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.source_name
     *
     * @param sourceName the value for bond_wallet_detail.source_name
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.source_account
     *
     * @return the value of bond_wallet_detail.source_account
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public String getSourceAccount() {
        return sourceAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.source_account
     *
     * @param sourceAccount the value for bond_wallet_detail.source_account
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setSourceAccount(String sourceAccount) {
        this.sourceAccount = sourceAccount == null ? null : sourceAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.operation_type
     *
     * @return the value of bond_wallet_detail.operation_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Integer getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.operation_type
     *
     * @param operationType the value for bond_wallet_detail.operation_type
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.payer_desc
     *
     * @return the value of bond_wallet_detail.payer_desc
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public String getPayerDesc() {
        return payerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.payer_desc
     *
     * @param payerDesc the value for bond_wallet_detail.payer_desc
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setPayerDesc(String payerDesc) {
        this.payerDesc = payerDesc == null ? null : payerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.payee_desc
     *
     * @return the value of bond_wallet_detail.payee_desc
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public String getPayeeDesc() {
        return payeeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.payee_desc
     *
     * @param payeeDesc the value for bond_wallet_detail.payee_desc
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setPayeeDesc(String payeeDesc) {
        this.payeeDesc = payeeDesc == null ? null : payeeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet_detail.create_date
     *
     * @return the value of bond_wallet_detail.create_date
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet_detail.create_date
     *
     * @param createDate the value for bond_wallet_detail.create_date
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_wallet_detail
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BondWalletDetail other = (BondWalletDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayerWalletId() == null ? other.getPayerWalletId() == null : this.getPayerWalletId().equals(other.getPayerWalletId()))
            && (this.getPayeeWalletId() == null ? other.getPayeeWalletId() == null : this.getPayeeWalletId().equals(other.getPayeeWalletId()))
            && (this.getPayerGuaranteeWalletId() == null ? other.getPayerGuaranteeWalletId() == null : this.getPayerGuaranteeWalletId().equals(other.getPayerGuaranteeWalletId()))
            && (this.getPayeeGuaranteeWalletId() == null ? other.getPayeeGuaranteeWalletId() == null : this.getPayeeGuaranteeWalletId().equals(other.getPayeeGuaranteeWalletId()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getDealBillType() == null ? other.getDealBillType() == null : this.getDealBillType().equals(other.getDealBillType()))
            && (this.getDealBillId() == null ? other.getDealBillId() == null : this.getDealBillId().equals(other.getDealBillId()))
            && (this.getSourceType() == null ? other.getSourceType() == null : this.getSourceType().equals(other.getSourceType()))
            && (this.getSourceName() == null ? other.getSourceName() == null : this.getSourceName().equals(other.getSourceName()))
            && (this.getSourceAccount() == null ? other.getSourceAccount() == null : this.getSourceAccount().equals(other.getSourceAccount()))
            && (this.getOperationType() == null ? other.getOperationType() == null : this.getOperationType().equals(other.getOperationType()))
            && (this.getPayerDesc() == null ? other.getPayerDesc() == null : this.getPayerDesc().equals(other.getPayerDesc()))
            && (this.getPayeeDesc() == null ? other.getPayeeDesc() == null : this.getPayeeDesc().equals(other.getPayeeDesc()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_wallet_detail
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayerWalletId() == null) ? 0 : getPayerWalletId().hashCode());
        result = prime * result + ((getPayeeWalletId() == null) ? 0 : getPayeeWalletId().hashCode());
        result = prime * result + ((getPayerGuaranteeWalletId() == null) ? 0 : getPayerGuaranteeWalletId().hashCode());
        result = prime * result + ((getPayeeGuaranteeWalletId() == null) ? 0 : getPayeeGuaranteeWalletId().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getDealBillType() == null) ? 0 : getDealBillType().hashCode());
        result = prime * result + ((getDealBillId() == null) ? 0 : getDealBillId().hashCode());
        result = prime * result + ((getSourceType() == null) ? 0 : getSourceType().hashCode());
        result = prime * result + ((getSourceName() == null) ? 0 : getSourceName().hashCode());
        result = prime * result + ((getSourceAccount() == null) ? 0 : getSourceAccount().hashCode());
        result = prime * result + ((getOperationType() == null) ? 0 : getOperationType().hashCode());
        result = prime * result + ((getPayerDesc() == null) ? 0 : getPayerDesc().hashCode());
        result = prime * result + ((getPayeeDesc() == null) ? 0 : getPayeeDesc().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_wallet_detail
     *
     * @mbggenerated Fri Feb 06 10:19:16 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payerWalletId=").append(payerWalletId);
        sb.append(", payeeWalletId=").append(payeeWalletId);
        sb.append(", payerGuaranteeWalletId=").append(payerGuaranteeWalletId);
        sb.append(", payeeGuaranteeWalletId=").append(payeeGuaranteeWalletId);
        sb.append(", amount=").append(amount);
        sb.append(", dealBillType=").append(dealBillType);
        sb.append(", dealBillId=").append(dealBillId);
        sb.append(", sourceType=").append(sourceType);
        sb.append(", sourceName=").append(sourceName);
        sb.append(", sourceAccount=").append(sourceAccount);
        sb.append(", operationType=").append(operationType);
        sb.append(", payerDesc=").append(payerDesc);
        sb.append(", payeeDesc=").append(payeeDesc);
        sb.append(", createDate=").append(createDate);
        sb.append("]");
        return sb.toString();
    }
}