package com.epeisong.net.ws.utils;

import java.io.Serializable;

public class BondWallet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet.id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet.bond_wallet_id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    private Integer bondWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet.user_wallet_id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    private Integer userWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet.normal_amount
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    private Long normalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet.frozn_amount
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    private Long frozenAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet.create_date
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_wallet.update_date
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    private Long updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bond_wallet
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet.id
     *
     * @return the value of bond_wallet.id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet.id
     *
     * @param id the value for bond_wallet.id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet.bond_wallet_id
     *
     * @return the value of bond_wallet.bond_wallet_id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public Integer getBondWalletId() {
        return bondWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet.bond_wallet_id
     *
     * @param bondWalletId the value for bond_wallet.bond_wallet_id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public void setBondWalletId(Integer bondWalletId) {
        this.bondWalletId = bondWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet.user_wallet_id
     *
     * @return the value of bond_wallet.user_wallet_id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public Integer getUserWalletId() {
        return userWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet.user_wallet_id
     *
     * @param userWalletId the value for bond_wallet.user_wallet_id
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public void setUserWalletId(Integer userWalletId) {
        this.userWalletId = userWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet.normal_amount
     *
     * @return the value of bond_wallet.normal_amount
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public Long getNormalAmount() {
        return normalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet.normal_amount
     *
     * @param normalAmount the value for bond_wallet.normal_amount
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public void setNormalAmount(Long normalAmount) {
        this.normalAmount = normalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet.frozn_amount
     *
     * @return the value of bond_wallet.frozn_amount
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public Long getFrozenAmount() {
        return frozenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet.frozn_amount
     *
     * @param froznAmount the value for bond_wallet.frozn_amount
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public void setFrozenAmount(Long frozenAmount) {
        this.frozenAmount = frozenAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet.create_date
     *
     * @return the value of bond_wallet.create_date
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet.create_date
     *
     * @param createDate the value for bond_wallet.create_date
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_wallet.update_date
     *
     * @return the value of bond_wallet.update_date
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public Long getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_wallet.update_date
     *
     * @param updateDate the value for bond_wallet.update_date
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_wallet
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BondWallet other = (BondWallet) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBondWalletId() == null ? other.getBondWalletId() == null : this.getBondWalletId().equals(other.getBondWalletId()))
            && (this.getUserWalletId() == null ? other.getUserWalletId() == null : this.getUserWalletId().equals(other.getUserWalletId()))
            && (this.getNormalAmount() == null ? other.getNormalAmount() == null : this.getNormalAmount().equals(other.getNormalAmount()))
            && (this.getFrozenAmount() == null ? other.getFrozenAmount() == null : this.getFrozenAmount().equals(other.getFrozenAmount()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_wallet
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBondWalletId() == null) ? 0 : getBondWalletId().hashCode());
        result = prime * result + ((getUserWalletId() == null) ? 0 : getUserWalletId().hashCode());
        result = prime * result + ((getNormalAmount() == null) ? 0 : getNormalAmount().hashCode());
        result = prime * result + ((getFrozenAmount() == null) ? 0 : getFrozenAmount().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_wallet
     *
     * @mbggenerated Mon Jan 26 17:26:57 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bondWalletId=").append(bondWalletId);
        sb.append(", userWalletId=").append(userWalletId);
        sb.append(", normalAmount=").append(normalAmount);
        sb.append(", frozenAmount=").append(frozenAmount);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}