package com.epeisong.net.ws.utils;

import java.io.Serializable;
import java.util.Date;

public class CustomServiceTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.id
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.logistics_id
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private Integer logisticsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.user_account
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.user_name
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.contact_tel
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.type
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.detail
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.result
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.status
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.create_date
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.update_date
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_service_task.sync_index
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private Integer syncIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table custom_service_task
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.id
     *
     * @return the value of custom_service_task.id
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.id
     *
     * @param id the value for custom_service_task.id
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.logistics_id
     *
     * @return the value of custom_service_task.logistics_id
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public Integer getLogisticsId() {
        return logisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.logistics_id
     *
     * @param logisticsId the value for custom_service_task.logistics_id
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setLogisticsId(Integer logisticsId) {
        this.logisticsId = logisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.user_account
     *
     * @return the value of custom_service_task.user_account
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.user_account
     *
     * @param userAccount the value for custom_service_task.user_account
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.user_name
     *
     * @return the value of custom_service_task.user_name
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.user_name
     *
     * @param userName the value for custom_service_task.user_name
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.contact_tel
     *
     * @return the value of custom_service_task.contact_tel
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.contact_tel
     *
     * @param contactTel the value for custom_service_task.contact_tel
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel == null ? null : contactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.type
     *
     * @return the value of custom_service_task.type
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.type
     *
     * @param type the value for custom_service_task.type
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.detail
     *
     * @return the value of custom_service_task.detail
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.detail
     *
     * @param detail the value for custom_service_task.detail
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.result
     *
     * @return the value of custom_service_task.result
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.result
     *
     * @param result the value for custom_service_task.result
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.status
     *
     * @return the value of custom_service_task.status
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.status
     *
     * @param status the value for custom_service_task.status
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.create_date
     *
     * @return the value of custom_service_task.create_date
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.create_date
     *
     * @param createDate the value for custom_service_task.create_date
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.update_date
     *
     * @return the value of custom_service_task.update_date
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.update_date
     *
     * @param updateDate the value for custom_service_task.update_date
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_service_task.sync_index
     *
     * @return the value of custom_service_task.sync_index
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public Integer getSyncIndex() {
        return syncIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_service_task.sync_index
     *
     * @param syncIndex the value for custom_service_task.sync_index
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    public void setSyncIndex(Integer syncIndex) {
        this.syncIndex = syncIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_service_task
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CustomServiceTask other = (CustomServiceTask) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLogisticsId() == null ? other.getLogisticsId() == null : this.getLogisticsId().equals(other.getLogisticsId()))
            && (this.getUserAccount() == null ? other.getUserAccount() == null : this.getUserAccount().equals(other.getUserAccount()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getContactTel() == null ? other.getContactTel() == null : this.getContactTel().equals(other.getContactTel()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getSyncIndex() == null ? other.getSyncIndex() == null : this.getSyncIndex().equals(other.getSyncIndex()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_service_task
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLogisticsId() == null) ? 0 : getLogisticsId().hashCode());
        result = prime * result + ((getUserAccount() == null) ? 0 : getUserAccount().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getContactTel() == null) ? 0 : getContactTel().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getSyncIndex() == null) ? 0 : getSyncIndex().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_service_task
     *
     * @mbggenerated Thu Mar 19 11:41:32 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", logisticsId=").append(logisticsId);
        sb.append(", userAccount=").append(userAccount);
        sb.append(", userName=").append(userName);
        sb.append(", contactTel=").append(contactTel);
        sb.append(", type=").append(type);
        sb.append(", detail=").append(detail);
        sb.append(", result=").append(result);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", syncIndex=").append(syncIndex);
        sb.append("]");
        return sb.toString();
    }
}