package com.epeisong.net.ws.utils;

import java.io.Serializable;

public class Task implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.payer_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Integer payerWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.payee_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Integer payeeWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.other_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Integer otherWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.amount
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.deal_bill_type
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Integer dealBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.deal_bill_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Integer dealBillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.operation_type
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Integer operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.status
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.payer_desc
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private String payerDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.payee_desc
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private String payeeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.create_date
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guarantee_task.update_date
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private Long updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guarantee_task
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.id
     *
     * @return the value of guarantee_task.id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.id
     *
     * @param id the value for guarantee_task.id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.payer_wallet_id
     *
     * @return the value of guarantee_task.payer_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Integer getPayerWalletId() {
        return payerWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.payer_wallet_id
     *
     * @param payerWalletId the value for guarantee_task.payer_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setPayerWalletId(Integer payerWalletId) {
        this.payerWalletId = payerWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.payee_wallet_id
     *
     * @return the value of guarantee_task.payee_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Integer getPayeeWalletId() {
        return payeeWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.payee_wallet_id
     *
     * @param payeeWalletId the value for guarantee_task.payee_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setPayeeWalletId(Integer payeeWalletId) {
        this.payeeWalletId = payeeWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.other_wallet_id
     *
     * @return the value of guarantee_task.other_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Integer getOtherWalletId() {
        return otherWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.other_wallet_id
     *
     * @param otherWalletId the value for guarantee_task.other_wallet_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setOtherWalletId(Integer otherWalletId) {
        this.otherWalletId = otherWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.amount
     *
     * @return the value of guarantee_task.amount
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.amount
     *
     * @param amount the value for guarantee_task.amount
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.deal_bill_type
     *
     * @return the value of guarantee_task.deal_bill_type
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Integer getDealBillType() {
        return dealBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.deal_bill_type
     *
     * @param dealBillType the value for guarantee_task.deal_bill_type
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setDealBillType(Integer dealBillType) {
        this.dealBillType = dealBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.deal_bill_id
     *
     * @return the value of guarantee_task.deal_bill_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Integer getDealBillId() {
        return dealBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.deal_bill_id
     *
     * @param dealBillId the value for guarantee_task.deal_bill_id
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setDealBillId(Integer dealBillId) {
        this.dealBillId = dealBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.operation_type
     *
     * @return the value of guarantee_task.operation_type
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Integer getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.operation_type
     *
     * @param operationType the value for guarantee_task.operation_type
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.status
     *
     * @return the value of guarantee_task.status
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.status
     *
     * @param status the value for guarantee_task.status
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.payer_desc
     *
     * @return the value of guarantee_task.payer_desc
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public String getPayerDesc() {
        return payerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.payer_desc
     *
     * @param payerDesc the value for guarantee_task.payer_desc
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setPayerDesc(String payerDesc) {
        this.payerDesc = payerDesc == null ? null : payerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.payee_desc
     *
     * @return the value of guarantee_task.payee_desc
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public String getPayeeDesc() {
        return payeeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.payee_desc
     *
     * @param payeeDesc the value for guarantee_task.payee_desc
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setPayeeDesc(String payeeDesc) {
        this.payeeDesc = payeeDesc == null ? null : payeeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.create_date
     *
     * @return the value of guarantee_task.create_date
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.create_date
     *
     * @param createDate the value for guarantee_task.create_date
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guarantee_task.update_date
     *
     * @return the value of guarantee_task.update_date
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public Long getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guarantee_task.update_date
     *
     * @param updateDate the value for guarantee_task.update_date
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_task
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Task other = (Task) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayerWalletId() == null ? other.getPayerWalletId() == null : this.getPayerWalletId().equals(other.getPayerWalletId()))
            && (this.getPayeeWalletId() == null ? other.getPayeeWalletId() == null : this.getPayeeWalletId().equals(other.getPayeeWalletId()))
            && (this.getOtherWalletId() == null ? other.getOtherWalletId() == null : this.getOtherWalletId().equals(other.getOtherWalletId()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getDealBillType() == null ? other.getDealBillType() == null : this.getDealBillType().equals(other.getDealBillType()))
            && (this.getDealBillId() == null ? other.getDealBillId() == null : this.getDealBillId().equals(other.getDealBillId()))
            && (this.getOperationType() == null ? other.getOperationType() == null : this.getOperationType().equals(other.getOperationType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getPayerDesc() == null ? other.getPayerDesc() == null : this.getPayerDesc().equals(other.getPayerDesc()))
            && (this.getPayeeDesc() == null ? other.getPayeeDesc() == null : this.getPayeeDesc().equals(other.getPayeeDesc()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_task
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayerWalletId() == null) ? 0 : getPayerWalletId().hashCode());
        result = prime * result + ((getPayeeWalletId() == null) ? 0 : getPayeeWalletId().hashCode());
        result = prime * result + ((getOtherWalletId() == null) ? 0 : getOtherWalletId().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getDealBillType() == null) ? 0 : getDealBillType().hashCode());
        result = prime * result + ((getDealBillId() == null) ? 0 : getDealBillId().hashCode());
        result = prime * result + ((getOperationType() == null) ? 0 : getOperationType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getPayerDesc() == null) ? 0 : getPayerDesc().hashCode());
        result = prime * result + ((getPayeeDesc() == null) ? 0 : getPayeeDesc().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guarantee_task
     *
     * @mbggenerated Wed Feb 04 11:05:05 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payerWalletId=").append(payerWalletId);
        sb.append(", payeeWalletId=").append(payeeWalletId);
        sb.append(", otherWalletId=").append(otherWalletId);
        sb.append(", amount=").append(amount);
        sb.append(", dealBillType=").append(dealBillType);
        sb.append(", dealBillId=").append(dealBillId);
        sb.append(", operationType=").append(operationType);
        sb.append(", status=").append(status);
        sb.append(", payerDesc=").append(payerDesc);
        sb.append(", payeeDesc=").append(payeeDesc);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}