package com.epeisong.net.ws.utils;

import java.io.Serializable;

public class WithdrawTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.payer_wallet_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer payerWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.amount
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.payee_type
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer payeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.open_bank_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String openBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.bank_code
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.bank_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.bank_region_code
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer bankRegionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.bank_region_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String bankRegionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.payee_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String payeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.payee_account
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String payeeAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.serial_number
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.status
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.create_date
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.update_date
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Long updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.sync_index
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer syncIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.withdraw_wallet_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer withdrawWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.note
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.sub_status
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer subStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.payer_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private String payerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.payer_logistics_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer payerLogisticsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw_task.payer_logistics_type
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private Integer payerLogisticsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table withdraw_task
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.id
     *
     * @return the value of withdraw_task.id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.id
     *
     * @param id the value for withdraw_task.id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.payer_wallet_id
     *
     * @return the value of withdraw_task.payer_wallet_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getPayerWalletId() {
        return payerWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.payer_wallet_id
     *
     * @param payerWalletId the value for withdraw_task.payer_wallet_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setPayerWalletId(Integer payerWalletId) {
        this.payerWalletId = payerWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.amount
     *
     * @return the value of withdraw_task.amount
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.amount
     *
     * @param amount the value for withdraw_task.amount
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.payee_type
     *
     * @return the value of withdraw_task.payee_type
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getPayeeType() {
        return payeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.payee_type
     *
     * @param payeeType the value for withdraw_task.payee_type
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setPayeeType(Integer payeeType) {
        this.payeeType = payeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.open_bank_name
     *
     * @return the value of withdraw_task.open_bank_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getOpenBankName() {
        return openBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.open_bank_name
     *
     * @param openBankName the value for withdraw_task.open_bank_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setOpenBankName(String openBankName) {
        this.openBankName = openBankName == null ? null : openBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.bank_code
     *
     * @return the value of withdraw_task.bank_code
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.bank_code
     *
     * @param bankCode the value for withdraw_task.bank_code
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.bank_name
     *
     * @return the value of withdraw_task.bank_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.bank_name
     *
     * @param bankName the value for withdraw_task.bank_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.bank_region_code
     *
     * @return the value of withdraw_task.bank_region_code
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getBankRegionCode() {
        return bankRegionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.bank_region_code
     *
     * @param bankRegionCode the value for withdraw_task.bank_region_code
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setBankRegionCode(Integer bankRegionCode) {
        this.bankRegionCode = bankRegionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.bank_region_name
     *
     * @return the value of withdraw_task.bank_region_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getBankRegionName() {
        return bankRegionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.bank_region_name
     *
     * @param bankRegionName the value for withdraw_task.bank_region_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setBankRegionName(String bankRegionName) {
        this.bankRegionName = bankRegionName == null ? null : bankRegionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.payee_name
     *
     * @return the value of withdraw_task.payee_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.payee_name
     *
     * @param payeeName the value for withdraw_task.payee_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName == null ? null : payeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.payee_account
     *
     * @return the value of withdraw_task.payee_account
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getPayeeAccount() {
        return payeeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.payee_account
     *
     * @param payeeAccount the value for withdraw_task.payee_account
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setPayeeAccount(String payeeAccount) {
        this.payeeAccount = payeeAccount == null ? null : payeeAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.serial_number
     *
     * @return the value of withdraw_task.serial_number
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.serial_number
     *
     * @param serialNumber the value for withdraw_task.serial_number
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.status
     *
     * @return the value of withdraw_task.status
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.status
     *
     * @param status the value for withdraw_task.status
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.create_date
     *
     * @return the value of withdraw_task.create_date
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.create_date
     *
     * @param createDate the value for withdraw_task.create_date
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.update_date
     *
     * @return the value of withdraw_task.update_date
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Long getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.update_date
     *
     * @param updateDate the value for withdraw_task.update_date
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.sync_index
     *
     * @return the value of withdraw_task.sync_index
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getSyncIndex() {
        return syncIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.sync_index
     *
     * @param syncIndex the value for withdraw_task.sync_index
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setSyncIndex(Integer syncIndex) {
        this.syncIndex = syncIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.withdraw_wallet_id
     *
     * @return the value of withdraw_task.withdraw_wallet_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getWithdrawWalletId() {
        return withdrawWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.withdraw_wallet_id
     *
     * @param withdrawWalletId the value for withdraw_task.withdraw_wallet_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setWithdrawWalletId(Integer withdrawWalletId) {
        this.withdrawWalletId = withdrawWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.note
     *
     * @return the value of withdraw_task.note
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.note
     *
     * @param note the value for withdraw_task.note
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.sub_status
     *
     * @return the value of withdraw_task.sub_status
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getSubStatus() {
        return subStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.sub_status
     *
     * @param subStatus the value for withdraw_task.sub_status
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setSubStatus(Integer subStatus) {
        this.subStatus = subStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.payer_name
     *
     * @return the value of withdraw_task.payer_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.payer_name
     *
     * @param payerName the value for withdraw_task.payer_name
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.payer_logistics_id
     *
     * @return the value of withdraw_task.payer_logistics_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getPayerLogisticsId() {
        return payerLogisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.payer_logistics_id
     *
     * @param payerLogisticsId the value for withdraw_task.payer_logistics_id
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setPayerLogisticsId(Integer payerLogisticsId) {
        this.payerLogisticsId = payerLogisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw_task.payer_logistics_type
     *
     * @return the value of withdraw_task.payer_logistics_type
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public Integer getPayerLogisticsType() {
        return payerLogisticsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw_task.payer_logistics_type
     *
     * @param payerLogisticsType the value for withdraw_task.payer_logistics_type
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    public void setPayerLogisticsType(Integer payerLogisticsType) {
        this.payerLogisticsType = payerLogisticsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_task
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WithdrawTask other = (WithdrawTask) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayerWalletId() == null ? other.getPayerWalletId() == null : this.getPayerWalletId().equals(other.getPayerWalletId()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getPayeeType() == null ? other.getPayeeType() == null : this.getPayeeType().equals(other.getPayeeType()))
            && (this.getOpenBankName() == null ? other.getOpenBankName() == null : this.getOpenBankName().equals(other.getOpenBankName()))
            && (this.getBankCode() == null ? other.getBankCode() == null : this.getBankCode().equals(other.getBankCode()))
            && (this.getBankName() == null ? other.getBankName() == null : this.getBankName().equals(other.getBankName()))
            && (this.getBankRegionCode() == null ? other.getBankRegionCode() == null : this.getBankRegionCode().equals(other.getBankRegionCode()))
            && (this.getBankRegionName() == null ? other.getBankRegionName() == null : this.getBankRegionName().equals(other.getBankRegionName()))
            && (this.getPayeeName() == null ? other.getPayeeName() == null : this.getPayeeName().equals(other.getPayeeName()))
            && (this.getPayeeAccount() == null ? other.getPayeeAccount() == null : this.getPayeeAccount().equals(other.getPayeeAccount()))
            && (this.getSerialNumber() == null ? other.getSerialNumber() == null : this.getSerialNumber().equals(other.getSerialNumber()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getSyncIndex() == null ? other.getSyncIndex() == null : this.getSyncIndex().equals(other.getSyncIndex()))
            && (this.getWithdrawWalletId() == null ? other.getWithdrawWalletId() == null : this.getWithdrawWalletId().equals(other.getWithdrawWalletId()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()))
            && (this.getSubStatus() == null ? other.getSubStatus() == null : this.getSubStatus().equals(other.getSubStatus()))
            && (this.getPayerName() == null ? other.getPayerName() == null : this.getPayerName().equals(other.getPayerName()))
            && (this.getPayerLogisticsId() == null ? other.getPayerLogisticsId() == null : this.getPayerLogisticsId().equals(other.getPayerLogisticsId()))
            && (this.getPayerLogisticsType() == null ? other.getPayerLogisticsType() == null : this.getPayerLogisticsType().equals(other.getPayerLogisticsType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_task
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayerWalletId() == null) ? 0 : getPayerWalletId().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getPayeeType() == null) ? 0 : getPayeeType().hashCode());
        result = prime * result + ((getOpenBankName() == null) ? 0 : getOpenBankName().hashCode());
        result = prime * result + ((getBankCode() == null) ? 0 : getBankCode().hashCode());
        result = prime * result + ((getBankName() == null) ? 0 : getBankName().hashCode());
        result = prime * result + ((getBankRegionCode() == null) ? 0 : getBankRegionCode().hashCode());
        result = prime * result + ((getBankRegionName() == null) ? 0 : getBankRegionName().hashCode());
        result = prime * result + ((getPayeeName() == null) ? 0 : getPayeeName().hashCode());
        result = prime * result + ((getPayeeAccount() == null) ? 0 : getPayeeAccount().hashCode());
        result = prime * result + ((getSerialNumber() == null) ? 0 : getSerialNumber().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getSyncIndex() == null) ? 0 : getSyncIndex().hashCode());
        result = prime * result + ((getWithdrawWalletId() == null) ? 0 : getWithdrawWalletId().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        result = prime * result + ((getSubStatus() == null) ? 0 : getSubStatus().hashCode());
        result = prime * result + ((getPayerName() == null) ? 0 : getPayerName().hashCode());
        result = prime * result + ((getPayerLogisticsId() == null) ? 0 : getPayerLogisticsId().hashCode());
        result = prime * result + ((getPayerLogisticsType() == null) ? 0 : getPayerLogisticsType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw_task
     *
     * @mbggenerated Mon Mar 09 18:02:56 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", payerWalletId=").append(payerWalletId);
        sb.append(", amount=").append(amount);
        sb.append(", payeeType=").append(payeeType);
        sb.append(", openBankName=").append(openBankName);
        sb.append(", bankCode=").append(bankCode);
        sb.append(", bankName=").append(bankName);
        sb.append(", bankRegionCode=").append(bankRegionCode);
        sb.append(", bankRegionName=").append(bankRegionName);
        sb.append(", payeeName=").append(payeeName);
        sb.append(", payeeAccount=").append(payeeAccount);
        sb.append(", serialNumber=").append(serialNumber);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", syncIndex=").append(syncIndex);
        sb.append(", withdrawWalletId=").append(withdrawWalletId);
        sb.append(", note=").append(note);
        sb.append(", subStatus=").append(subStatus);
        sb.append(", payerName=").append(payerName);
        sb.append(", payerLogisticsId=").append(payerLogisticsId);
        sb.append(", payerLogisticsType=").append(payerLogisticsType);
        sb.append("]");
        return sb.toString();
    }
}